import { PageHero } from "@/components/public/page-hero"
import { createPageMetadata } from "@/lib/seo"

export const metadata = createPageMetadata({
  title: "CIRC Privacy Policy",
  description: "Read how the Computing Innovation & Research Club at Mama Ngina University College handles website, membership application, and analytics information.",
  path: "/privacy",
  keywords: ["CIRC privacy policy", "MNUC website privacy", "membership application data"],
})

export default function PrivacyPage() {
  return (
    <div className="flex flex-col min-h-screen bg-surface-2">
      <PageHero badge="LEGAL // PRIVACY" title="Privacy Policy" subtitle="How CIRC handles information shared through this website and our club activities." size="sm" />
      <div className="max-w-4xl mx-auto px-6 py-16 w-full">
        <article className="bg-white rounded-3xl p-8 sm:p-12 border border-primary/10 shadow-[0_8px_30px_rgba(15,36,96,0.04)] space-y-8 text-main leading-relaxed">
          <p><strong className="text-primary font-bold">Last updated: October 1, 2026.</strong> This notice describes the practices of the Computing Innovation &amp; Research Club (CIRC) at Mama Ngina University College for information collected through this website. CIRC contact: <a className="text-accent-orange font-semibold hover:underline" href="mailto:circ@mnu.ac.ke">circ@mnu.ac.ke</a>.</p>
          <section><h2 className="font-display text-primary text-2xl font-bold mb-3">Information we collect</h2><p className="text-muted leading-relaxed">When you apply to join, we collect your name, student ID, department, year of study, email address, phone number, selected communities, skills, and application responses. When you contact us, we process the information you choose to send. Site administrators also add public event, gallery, team, and community information. Sign-in and security services may process account identifiers and technical logs. Google Analytics and Microsoft Clarity are enabled by default on public pages and receive technical and usage information such as pages viewed, interactions, browser and device details, and identifiers or cookies. Clarity may record how pages are used; form fields and sensitive content should be masked in the Clarity project settings.</p></section>
          <section><h2 className="font-display text-primary text-2xl font-bold mb-3">Purposes and legal grounds</h2><p className="text-muted leading-relaxed">We use application and contact information to review membership requests, communicate about club activities, organize events, and administer the club. We use account and security information to authenticate users, protect the service, and prevent misuse. We use Google Analytics and Microsoft Clarity by default on public pages to understand site usage and improve the website; they are not required to provide the public site. Depending on the context and applicable law, processing is based on your request or relationship with CIRC, our legitimate interests in operating and securing the club website, legal obligations, or your consent. The website does not provide an in-page analytics opt-out control. You may contact us to exercise rights that apply to you, including the right to object where provided by law; this does not affect processing already carried out.</p></section>
          <section><h2 className="font-display text-primary text-2xl font-bold mb-3">Service providers and international transfers</h2><p className="text-muted leading-relaxed">We share information only as needed with authorized club administrators and service providers that support hosting, database storage, authentication, image delivery, and analytics. Google and Microsoft may process analytics information under their own terms. These providers may process information in countries outside Kenya or your country of residence. Where required, we use an appropriate transfer mechanism and safeguards. We do not sell personal information. We do not use analytics for advertising in this website configuration.</p></section>
          <section><h2 className="font-display text-primary text-2xl font-bold mb-3">Retention and security</h2><p className="text-muted leading-relaxed">We keep information for as long as needed for the purposes described above, including handling applications, maintaining club records, resolving disputes, and meeting legal obligations, then delete or anonymize it where reasonably practicable. We use access controls and other reasonable safeguards, but no online service can guarantee absolute security. Access to application records is restricted to authorized administrators.</p></section>
          <section><h2 className="font-display text-primary text-2xl font-bold mb-3">Your rights and choices</h2><p className="text-muted leading-relaxed">Depending on where you live and the laws that apply, you may request access to, correction of, deletion of, or a copy of your personal information; object to or restrict certain processing; withdraw consent where processing relies on consent; or complain to a data protection authority. Kenya’s Data Protection Act provides rights including to be informed, access data, object to processing, and request correction or deletion of false or misleading data. US privacy rights vary by state and may include rights to know, access, correct, delete, or opt out of certain processing. EU/EEA residents may exercise rights under applicable data protection law and complain to their supervisory authority. To make a request, email <a className="text-accent-orange font-semibold hover:underline" href="mailto:circ@mnu.ac.ke">circ@mnu.ac.ke</a>; we may ask for information needed to verify and respond to it.</p></section>
          <section><h2 className="font-display text-primary text-2xl font-bold mb-3">Children and changes</h2><p className="text-muted leading-relaxed">This website is intended for university students and the wider university community, and is not directed to children under 18. We do not knowingly collect children’s personal data except where participation is lawful and any required parent or guardian authorization has been obtained. If you believe a child has provided personal information, contact us so we can review it. We may update this notice as our services or legal obligations change and will revise the date above.</p></section>
        </article>
      </div>
    </div>
  )
}
