/**
 * Public copy keeps the site crawlable and useful during a database outage.
 * The database remains the source of truth whenever it is available.
 */
const createdAt = new Date("2024-01-01T00:00:00.000Z")

export const FALLBACK_COMMUNITIES = [
  {
    id: "public-web-development",
    name: "Web Development",
    slug: "web-development",
    description: "Build modern web applications and digital experiences, from frontend interfaces to full-stack systems.",
    focusTags: ["React", "Next.js", "Node.js", "TypeScript", "Figma", "TailwindCSS"],
    heroImage: null,
    leadId: null,
    activities: [],
    createdAt,
    lead: null,
    events: [],
  },
  {
    id: "public-data-science",
    name: "Data Science and Modelling",
    slug: "data-science",
    description: "Explore statistical analysis, data visualisation, machine learning pipelines, and real-world data modelling.",
    focusTags: ["Python", "R", "Pandas", "NumPy", "Matplotlib", "SQL"],
    heroImage: null,
    leadId: null,
    activities: [],
    createdAt,
    lead: null,
    events: [],
  },
  {
    id: "public-ai-ml",
    name: "AI and Machine Learning",
    slug: "ai-ml",
    description: "Explore artificial intelligence and build intelligent systems, including neural networks, natural language processing, and computer vision.",
    focusTags: ["TensorFlow", "PyTorch", "Keras", "Scikit-learn", "OpenAI", "Hugging Face"],
    heroImage: null,
    leadId: null,
    activities: [],
    createdAt,
    lead: null,
    events: [],
  },
  {
    id: "public-web3",
    name: "Web3 and Blockchain",
    slug: "web3-blockchain",
    description: "Learn about blockchain technology, smart contracts, decentralized applications, and the infrastructure of Web3.",
    focusTags: ["Solidity", "Ethereum", "Hardhat", "IPFS", "Web3.js", "MetaMask"],
    heroImage: null,
    leadId: null,
    activities: [],
    createdAt,
    lead: null,
    events: [],
  },
  {
    id: "public-programming",
    name: "Programming Community",
    slug: "programming",
    description: "Strengthen programming skills through algorithms, data structures, competitive programming, and software fundamentals.",
    focusTags: ["C++", "Java", "Python", "Rust", "Algorithms", "LeetCode"],
    heroImage: null,
    leadId: null,
    activities: [],
    createdAt,
    lead: null,
    events: [],
  },
  {
    id: "public-iot",
    name: "Internet of Things",
    slug: "iot",
    description: "Connect physical devices to digital systems by building hardware and software projects with sensors and connected technology.",
    focusTags: ["Arduino", "Raspberry Pi", "MQTT", "C", "Sensors", "Edge Computing"],
    heroImage: null,
    leadId: null,
    activities: [],
    createdAt,
    lead: null,
    events: [],
  },
  {
    id: "public-networking-cybersecurity",
    name: "Networking and Cybersecurity",
    slug: "networking-cybersecurity",
    description: "Study network architecture, ethical security testing, cryptography, and the principles of protecting digital infrastructure.",
    focusTags: ["Network Security", "Ethical Hacking", "Cryptography", "Wireshark", "Kali Linux", "Firewalls"],
    heroImage: null,
    leadId: null,
    activities: [],
    createdAt,
    lead: null,
    events: [],
  },
]

